### ISSUE TITLE
Unbox failed

### ISSUE THREAD

**Issue by aportno** [smartcontractkit/truffle-starter-kit#118]
Steps:
1.  `npm install truffle -g`
2.  `mkdir myChainlinkProject`
3. `cd` myChainlinkProject
4. `truffle unbox smartcontractkit/box`

Error:

```
Error: Command failed: bash unbox.sh && rm unbox.sh
    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Object.installBoxDependencies (C:\Users\alexa\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\unbox.js:136:1)
    at Object.setUpBox (C:\Users\alexa\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\index.js:66:1)
    at C:\Users\alexa\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\alexa\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:5:42)
Truffle v5.3.14 (core: 5.3.14)
Node v14.17.0```

**Comment by aportno** [comment]
Resolved from prior issue raised
